export * from "./useCAPQueries";
export * from "./useNCCQueries";
export * from "./useRegulationQueries";
export * from "./useAssignmentQueries";
export * from "./useReportQueries";
export * from "./useEWSQueries";
export * from "./useAdminQueries";
export * from "./useDashboardQueries";
export * from "./useNotificationQueries";
export * from "./useAIQueries";
export * from "./useFileQueries";
export * from "./useObligationQueries";
export * from "./useLMQueries";
export { useTabActionCounts } from "@/hooks/useTabActionCounts";
export type { TabActionCounts } from "@/hooks/useTabActionCounts";
